### ISSUE TITLE
ChimeraOS Documentation

### ISSUE THREAD

**Issue by ruineka** [mikeroyal/Asus-ROG-Ally-Guide#2]
I see you are putting together a really good guide for the Ally! Would you be interested in joining the ChimeraOS discord to follow the news regarding development for the Ally and document the many "quirks" this device has?

Looking forward to hearing from you.

**Comment by mikeroyal** [comment]
Hi,  I would need to check my schedule because my daily job takes 10 hours out my day with the rest of my  free time split between family and maintaining dozens of other projects.  I can report that the latest ChimeraOS Alpha build is about 85% usable on the ROG Ally main issues being bluetooth connection and poor power management leading to bad battery life. Though, this mainly due to AMD  still upstreaming patches/fixes to the new Z1/Z1 Extreme chips. I think by the time Kernel 6.5 and MESA 23.3/23.4 graphics stack comes out is when ChimeraOS and other rolling Linux distros will be performing great on the ROG Ally.

**Comment by mikeroyal** [comment]
Also feel free to share this guide with anyone interested in the ROG Ally. Whether you game on Windows or Linux I want to make sure everyone has a great experinece.
